build pkg with 'mvn package'; add tomcat

diff --git a/packages/kafka-service-broker/packaging b/packages/kafka-service-broker/packaging
--- a/packages/kafka-service-broker/packaging
+++ b/packages/kafka-service-broker/packaging
@@ -12,4 +12,15 @@ chmod -R a+r jdk
 
 cd ${BOSH_INSTALL_TARGET}
 
-cp ${BOSH_COMPILE_TARGET}/kafka-service-broker/out/* .
+tar zxvf ${BOSH_COMPILE_TARGET}/uaa/apache-tomcat-8.0.39.tar.gz
+if [[ $? != 0 ]] ; then
+  echo "Cannot unpack Tomcat"
+  exit 1
+fi
+
+mv apache-tomcat-8.0.39 tomcat
+
+cd tomcat
+rm -rf webapps/*
+
+cp -a ${BOSH_COMPILE_TARGET}/kafka-service-broker/kafka-broker/target/kafka-broker.jar webapps/*
